name: Fetch Snow Data

on:
  schedule:
    - cron: '0 * * * *'  # every hour on the hour
  workflow_dispatch:     # allows manual run

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run snow data fetch script
        run: python scripts/fetch_snow_data.py

      - name: Commit and push data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/snow_data.json
          git commit -m "Update snow data" || echo "No changes to commit"
          git push
